Lua macros
func: defines literal with current function name.
check_args: don't need to pass name
get_gspace: use generated message
push_error: push error message and return 1
c_str: explicitly convert string literals to sring and then get const char *. useful when passing string concatenation expression to error message

fix log filename to match API